# Generated by Django 5.2.9 on 2026-06-10 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0002_province_updated_at_alter_district_code_and_more"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userrole",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_roles",
                to="regions.district",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "region")},
        ),
    ]
