# Generated by Django 5.2.9 on 2026-06-10 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="province",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code must be 2-5 uppercase letters only",
                        regex="^[A-Z0-9]{2,5}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code must be 2-5 uppercase letters only",
                        regex="^[A-Z0-9]{2,5}$",
                    )
                ],
            ),
        ),
    ]
