# Generated by Django 5.2.9 on 2026-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("koshi", "Koshi Province"),
                    ("madhesh", "Madhesh Province"),
                    ("bagmati", "Bagmati Province"),
                    ("gandaki", "Gandaki Province"),
                    ("lumbini", "Lumbini Province"),
                    ("karnali", "Karnali Province"),
                    ("sudurpashchim", "Sudurpashchim Province"),
                ],
                help_text="Only applicable for province staff.",
                max_length=50,
                null=True,
            ),
        ),
    ]
